# Generated by Django 4.1.3 on 2023-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
